"""Single source of truth for the source corpus, shared by fetch/build scripts and sources.md."""

SOURCES = [
    {"id": "amc-about", "url": "https://growwmf.in/about-us", "category": "amc-general", "scheme": None, "format": "html"},
    {"id": "scheme-largecap", "url": "https://www.growwmf.in/mutual-funds/groww-large-cap-fund-direct-growth", "category": "amc-scheme", "scheme": "Large Cap", "format": "html"},
    {"id": "scheme-multicap", "url": "https://www.growwmf.in/mutual-funds/groww-multicap-fund-direct-growth", "category": "amc-scheme", "scheme": "Multicap", "format": "html"},
    {"id": "scheme-elss", "url": "https://www.growwmf.in/mutual-funds/groww-elss-tax-saver-fund-direct-growth", "category": "amc-scheme", "scheme": "ELSS Tax Saver", "format": "html"},
    {"id": "scheme-liquid", "url": "https://www.growwmf.in/mutual-funds/groww-liquid-fund-direct-growth", "category": "amc-scheme", "scheme": "Liquid", "format": "html"},
    {"id": "sid-largecap", "url": "https://assets-netstorage.growwmf.in/compliance_docs/Downloads/SID/SID_Groww%20Large%20Cap%20Fund%20.pdf", "category": "amc-scheme", "scheme": "Large Cap", "format": "pdf"},
    {"id": "sid-multicap", "url": "https://assets-netstorage.growwmf.in/compliance_docs/Downloads/SID/SID_Groww%20Multicap%20Fund.pdf", "category": "amc-scheme", "scheme": "Multicap", "format": "pdf"},
    {"id": "kim-multicap", "url": "https://assets-netstorage.growwmf.in/compliance_docs/Downloads/KIM/KIM_Groww%20Multicap%20Fund.pdf", "category": "amc-scheme", "scheme": "Multicap", "format": "pdf"},
    {"id": "sid-elss", "url": "https://assets-netstorage.growwmf.in/compliance_docs/Downloads/SID/SID_Groww%20ELSS%20Tax%20Saver%20Fund.pdf", "category": "amc-scheme", "scheme": "ELSS Tax Saver", "format": "pdf"},
    {"id": "kim-elss", "url": "https://assets-netstorage.growwmf.in/compliance_docs/Downloads/KIM/KIM_Groww%20ELSS%20Tax%20Saver%20Fund.pdf", "category": "amc-scheme", "scheme": "ELSS Tax Saver", "format": "pdf"},
    {"id": "sid-liquid", "url": "https://assets-netstorage.growwmf.in/compliance_docs/Downloads/SID/SID_Groww%20Liquid%20Fund.pdf", "category": "amc-scheme", "scheme": "Liquid", "format": "pdf"},
    {"id": "factsheet", "url": "https://assets-netstorage.growwmf.in/compliance_docs/Downloads/Fact%20Sheet/2025%20-%202026/Monthly%20Factsheet%20-%20Jan%2026.pdf", "category": "amc-general", "scheme": None, "format": "pdf"},
    {"id": "investor-faqs", "url": "https://cms-resources.growwmf.in/uploads/FA_Qs_for_Investors_Valid_Handle_21419eab26.pdf", "category": "amc-general", "scheme": None, "format": "pdf"},
    {"id": "kyc-faqs", "url": "https://growwmf.in/new-kyc-regulations", "category": "amc-general", "scheme": None, "format": "html"},
    {"id": "capital-gains-guide", "url": "https://groww.in/blog/how-to-get-capital-gains-statement-for-mutual-fund-investments", "category": "amc-general", "scheme": None, "format": "html"},
    {"id": "amfi-riskometer-levels", "url": "https://www.mutualfundssahihai.com/en/what-riskometer-and-what-are-different-levels", "category": "amfi", "scheme": None, "format": "html"},
    {"id": "amfi-riskometer-derived", "url": "https://www.mutualfundssahihai.com/en/how-riskometer-scheme-derived", "category": "amfi", "scheme": None, "format": "html"},
    {"id": "amfi-tri", "url": "https://www.mutualfundssahihai.com/en/what-total-return-index-tri-mutual-fund", "category": "amfi", "scheme": None, "format": "html"},
    {"id": "amfi-lockin", "url": "https://www.mutualfundssahihai.com/en/what-is-lock-in-period", "category": "amfi", "scheme": None, "format": "html"},
    {"id": "amfi-expenses", "url": "https://www.mutualfundssahihai.com/en/what-are-expenses-incurred-mutual-fund-scheme", "category": "amfi", "scheme": None, "format": "html"},
    {"id": "amfi-loads", "url": "https://www.mutualfundssahihai.com/en/what-are-loads", "category": "amfi", "scheme": None, "format": "html"},
    {"id": "amfi-benchmarks", "url": "https://www.amfiindia.com/otherdata/listofbenchmarkindices", "category": "amfi", "scheme": None, "format": "html"},
    {"id": "sebi-riskometer-circular", "url": "https://www.sebi.gov.in/legal/circulars/oct-2020/circular-on-product-labeling-in-mutual-fund-schemes-risk-o-meter_47796.html", "category": "sebi", "scheme": None, "format": "html"},
    {"id": "sebi-investor-faqs", "url": "https://www.sebi.gov.in/sebi_data/faqfiles/sep-2024/1727242783639.pdf", "category": "sebi", "scheme": None, "format": "pdf"},
    {"id": "kfintech-cas", "url": "https://mfs.kfintech.com/investor/General/CapitalGainsLossAccountStatement", "category": "amc-general", "scheme": None, "format": "html"},
]
